//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public string Qid { get; set; }
        public string UserId { get; set; }
        public string SkinId { get; set; }
        public string QusText { get; set; }
        public string Phone { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual SkinType SkinType { get; set; }
    }
}
