//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentM4
{
    using AssignmentM4.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class SkinType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkinType()
        {
            this.Question = new HashSet<Question>();
        }
    
        public string SkinId { get; set; }
        public string Name { get; set; }
        public string Pic { get; set; }
        public string Detail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Question { get; set; }

        public LoginViewModel LoginViewModel { get; set; }
    }
}
